site_name: Documentation Magasin ERPNext
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
plugins:
  - glightbox

nav:
  - Introduction: index.md
  - Guide Administrateur:
      - Aperçu: admin/overview.md
      - Configuration: admin/setup.md
      - Opérations Quotidiennes: admin/daily_ops.md
  - Guide Caissier:
      - Premiers Pas: cashier/getting_started.md
      - Ventes: cashier/sales.md
      - Retours: cashier/return.md
      - FAQ: cashier/faq.md
  - Guide Employé Entrepôt:
      - Premiers Pas: warehouse-worker/getting_started.md
      - Ventes: warehouse-worker/sales.md
      - Stock: warehouse-worker/stock.md
      - FAQ: warehouse-worker/faq.md